Added support for recursive pattern in dependency xml files
carbonated-dev/o3de pull request #182
Opened 2024-03-13 22:41 UTC by alexeykostin

## What does this PR do?

Added support for recursive pattern in dependency xml files

One can use the pattern 

`foo/bar/**`

to add dependency for all assets under `foo/bar/` path hint.

Use 

`foo/bar/**/*.png`

to match all `*.png` assets under `foo/bar/` path hint.

## How was this PR tested?

Tested locally by adding / removing the recursive pattern from existing `_dependency.xml`'s and checking the resulting asset lists

2024-03-16 03:04 UTC, carb-lloyd commented
@alexeykostin  - let's simplify this back to the way you had before, in that:
foo/bar/* --> non-recursive, everything in that folder
foo/bar/** --> recursive, everything in every child folder.

And remove the foo/bar/**/*.png support

If needed we can look at better regex etc support later, but it's not really worth the effort for now

2024-03-19 17:03 UTC, carb-lloyd requested changes
Requesting changes:
Remove **/.*
Keep support /** and verify.  Create new pr in our project w/ update to our seedlists

2024-03-19 23:13 UTC, carb-lloyd requested changes

2024-03-19 23:13 UTC, carb-lloyd commented on Code/Tools/AssetProcessor/native/AssetManager/PathDependencyManager.cpp
> +                                )
Small thing, but this makes diffs difficult during engine updates difficult.
Do this instead:
```
#if defined(CARBONATED)
if (!isExactDependency && isRecursiveDependency)
#else
if (!isExactDependency)
#endif
```

2024-03-20 14:22 UTC, carb-lloyd approved these changes

2024-03-20 18:17 UTC, carb-lloyd commented
@alexeykostin  - please merge and close when tested.

2024-03-20 19:17 UTC, alexeykostin commented
Tested locally.

2024-03-20 19:18 UTC, merged