Converted sys_assert definition from REGISTER_CVAR2_CB to AZ_CVAR
carbonated-dev/o3de pull request #190
Opened 2024-03-18 21:01 UTC by alexeykostin

## What does this PR do?

Converted sys_assert definition from REGISTER_CVAR2_CB to AZ_CVAR to make sure that the callback that sets the respective AZ::Environment variable is invoked.

## How was this PR tested?

Tested locally

2024-03-18 21:17 UTC, vmednonogov approved these changes
LGTM

2024-03-19 16:49 UTC, carb-lloyd commented
@alexeykostin Please remember to add me to every engine PR.

2024-03-19 16:53 UTC, carb-lloyd requested changes
Please place these into a namespace.

2024-03-19 16:53 UTC, carb-lloyd commented on Code/Legacy/CrySystem/SystemInit.cpp
> +
Place this in a namespace (see rest of engine / project for examples). 

Suggest:

namespace Legacy::System::CVars
{
    AZ_CVAR(...)
}

2024-03-19 16:53 UTC, carb-lloyd commented on Code/Legacy/CrySystem/SystemInit.cpp
> +
Convert this to the new cvar registration too.

2024-03-19 16:57 UTC, carb-lloyd commented
You also need to go through the engine and fix up the references to the old "sys_asserts" cvar, and use the newly registered one instead.

Look at carb-lloyd/sys_asserts_cvar.

2024-03-19 20:17 UTC, carb-lloyd requested changes

2024-03-19 20:17 UTC, carb-lloyd commented on Code/Legacy/CrySystem/System.h
> +#if !defined(CARBONATED)
Move the comment in the #if !def block

2024-03-19 20:17 UTC, carb-lloyd commented on Code/Legacy/CrySystem/SystemInit.cpp
> -        }
Why were these lines removed?

If CARBONATED was not defined, this would result to:
```
if (g_cvars.sys_asserts == 2)
LogBuildInfo();
```

2024-03-19 20:36 UTC, carb-lloyd commented
You still need to figure out what to do about the sys_asserts usage in 
`Gems/ImGui/Code/Source/LYCommonMenu/ImGuiLYCommonMenu.cpp`

(Search the code for all references/usages of "sys_asserts" and ensure they use the new cvar)

2024-03-20 13:58 UTC, alexeykostin commented on Code/Legacy/CrySystem/System.h
> +#if !defined(CARBONATED)
Moved

2024-03-20 13:58 UTC, alexeykostin commented on Code/Legacy/CrySystem/SystemInit.cpp
> -        }
Reverted lost code

2024-03-20 19:16 UTC, alexeykostin commented
PR updated

2024-03-21 16:49 UTC, carb-lloyd approved these changes

2024-03-21 17:05 UTC, merged