Aefimov/memory tracing
carbonated-dev/o3de pull request #214
Opened 2024-04-11 13:59 UTC by aefimov3

## What does this PR do?

Add memory marker feature that speeds up memory slice creation.
Add memory tag feature that allows to track a particular feature memory.

## How was this PR tested?

Local test on Windows standalone client. The changes do not affect normal game/editor, there must be special define to turn memory tracking on.

2024-04-11 15:09 UTC, vmednonogov commented on Code/Framework/AzCore/AzCore/Memory/AllocationRecords.cpp
> +                memcpy(savedName, ai.m_name, nameLength + 1);
Could we use totalLength here

2024-04-11 15:09 UTC, vmednonogov commented on Code/Framework/AzCore/AzCore/Memory/AllocationRecords.cpp
> +                const size_t nameLength = strlen(ai.m_name);
Could we use totalLength only ( nameLength is not necessary)

2024-04-11 15:09 UTC, vmednonogov commented on Code/Framework/AzCore/AzCore/Memory/AllocationRecords.h
> +            unsigned int    m_tag;     ///< Latest mmeory tag
mmeory -> memory

2024-04-11 19:02 UTC, alexeykostin requested changes

2024-04-11 19:02 UTC, alexeykostin commented on Code/Framework/AzCore/AzCore/Memory/AllocatorManager.h
> +                //, m_line(0)  // TODO delete if not needed
Please delete if it is not needed.

2024-04-11 19:02 UTC, alexeykostin commented on Code/Framework/AzCore/AzCore/Memory/AllocatorManager.h
> +        /// Pop mmeory tag from stack
mmeory  -> memory

2024-04-11 19:02 UTC, alexeykostin commented on Code/Framework/AzCore/AzCore/Memory/AllocatorManager.h
> +        /// Protection from a recusrive call by the same thread
recusrive  -> recursive

2024-04-11 19:02 UTC, alexeykostin commented on Code/Framework/AzCore/AzCore/Memory/AllocatorManager.h
> +                AZ_Assert(!IsOverflow(), "Get, but overflow");
Is overflow ever possible?

2024-04-11 19:02 UTC, alexeykostin commented on Code/Framework/AzCore/AzCore/Script/ScriptSystemComponent.cpp
> +void ScriptSystemComponent::OnSystemTick()
This change is not required. I'd rather revert.

2024-04-11 19:02 UTC, alexeykostin commented on Code/Framework/AzCore/AzCore/Memory/MemoryMarker.h
> +
Extra line

2024-04-11 19:02 UTC, alexeykostin commented on Code/Framework/AzCore/AzCore/Script/ScriptSystemBus.h
> +        virtual int GetDefaultGarbageCollectSteps() = 0;
Can it be `const`?

2024-04-11 19:02 UTC, alexeykostin commented on Code/Framework/AzCore/AzCore/azcore_files.cmake
> +    Memory/MemoryMarker.cpp
It means these files will be included regardless CARBONATED. Please consider to guard these files content entirely by `#if CARBONATED .. #endif`

2024-04-16 17:56 UTC, aefimov3 commented on Code/Framework/AzCore/AzCore/Memory/AllocationRecords.cpp
> +                const size_t nameLength = strlen(ai.m_name);
This code piece is designed for extension, it might be I add more saved items there. So it is a good practice to use a component specific and a total variable.

2024-04-16 17:58 UTC, aefimov3 commented on Code/Framework/AzCore/AzCore/Memory/AllocationRecords.cpp
> +                memcpy(savedName, ai.m_name, nameLength + 1);
I changed the code to use name length as string lenght + 1, but I still keep separate total length for future extension.

2024-04-16 17:59 UTC, aefimov3 commented on Code/Framework/AzCore/AzCore/Memory/AllocationRecords.h
> +            unsigned int    m_tag;     ///< Latest mmeory tag
Fixed

2024-04-16 17:59 UTC, aefimov3 commented on Code/Framework/AzCore/AzCore/Memory/AllocatorManager.h
> +        /// Pop mmeory tag from stack
Fixed

2024-04-16 18:00 UTC, aefimov3 commented on Code/Framework/AzCore/AzCore/Memory/AllocatorManager.h
> +                //, m_line(0)  // TODO delete if not needed
Done

2024-04-16 18:00 UTC, aefimov3 commented on Code/Framework/AzCore/AzCore/Memory/AllocatorManager.h
> +        /// Protection from a recusrive call by the same thread
Fixed

2024-04-16 18:02 UTC, aefimov3 commented on Code/Framework/AzCore/AzCore/Memory/AllocatorManager.h
> +                AZ_Assert(!IsOverflow(), "Get, but overflow");
Yes, it is specially designed to overflow, that's why I use a custom container. It keeps the counter above the capacity, but does not store values, so it cannot Get(). If an overflow happens then nothing breaks, just the extra tags are not applied.

2024-04-16 18:05 UTC, aefimov3 commented on Code/Framework/AzCore/AzCore/Script/ScriptSystemComponent.cpp
> +void ScriptSystemComponent::OnSystemTick()
That looks annoying, I agree that it adds extra complexity when merging new o3de, but that's pretty minimal.

2024-04-16 18:06 UTC, aefimov3 commented on Code/Framework/AzCore/AzCore/Memory/MemoryMarker.h
> +
Deleted

2024-04-16 18:46 UTC, aefimov3 commented on Code/Framework/AzCore/AzCore/azcore_files.cmake
> +    Memory/MemoryMarker.cpp
Fixed, I added a more complex define fence.

2024-04-16 18:50 UTC, aefimov3 commented on Code/Framework/AzCore/AzCore/Script/ScriptSystemBus.h
> +        virtual int GetDefaultGarbageCollectSteps() = 0;
Added.

2024-04-16 20:10 UTC, alexeykostin approved these changes

2024-04-16 20:10 UTC, alexeykostin commented on Code/Framework/AzCore/AzCore/Script/ScriptSystemComponent.cpp
> +// ResetGarbageCollectStepsIfDefault
It should be `GetDefaultGarbageCollectSteps`

2024-04-16 20:25 UTC, aefimov3 commented on Code/Framework/AzCore/AzCore/Script/ScriptSystemComponent.cpp
> +// ResetGarbageCollectStepsIfDefault
Fixed

2024-04-17 09:19 UTC, merged