[LyShine] Use authored canvas size for UI canvas
carbonated-dev/o3de pull request #255
Opened 2024-05-17 12:53 UTC by alexeykostin

## What does this PR do?

[LyShine] Use authored canvas size for UI canvas

## How was this PR tested?

Tested on iPhone using the dev version of base application.

2024-05-17 18:04 UTC, aefimov3 commented on Gems/LyShine/Code/Source/UiCanvasComponent.cpp
> +                const AZ::Vector2 renderViewportSize = uiRenderer->GetViewportSize();
I wonder if it returns the screen resolution or the render resolution. You can test it by settings r_renderScale less than 1, then checking what is the result for viewportWidth & viewportHeight. We might have another issue here. Please test it and let me know. You can do it in runtime I believe by running console command r_renderScale = 0.8 or adding it to a setreg file.

2024-05-17 18:06 UTC, aefimov3 commented on Gems/LyShine/Code/Source/UiCanvasComponent.cpp
> +                const AZ::Vector2 renderViewportSize = uiRenderer->GetViewportSize();
I saw that with the world map and the game HUD UI the user input touch event comes in screen coordinates, so in theory this should return screen, NOT the reduced render.

2024-05-17 18:11 UTC, aefimov3 commented on Gems/LyShine/Code/Source/UiCanvasComponent.cpp
> +            m_targetCanvasSize.SetX(m_targetCanvasSize.GetY() * (canvasSize.GetX() / canvasSize.GetY()));
m_targetCanvasSize.GetY() * newAspectRatio looks better

2024-05-17 18:12 UTC, aefimov3 commented on Gems/LyShine/Code/Source/UiCanvasComponent.cpp
> +            m_targetCanvasSize.SetY(m_targetCanvasSize.GetX() * (canvasSize.GetY() / canvasSize.GetX()));
m_targetCanvasSize.GetX() / newAspectRatio looks better

2024-05-17 18:16 UTC, aefimov3 commented on Gems/LyShine/Code/Source/UiRenderer.cpp
> +        const AZ::RHI::Viewport& viewport = viewportContext->GetWindowContext()->GetViewport();
Please ensure that the feature works with r_renderScale = 0.8 or less. Just by looking at the code it is not easy to derive what viewports / resolutions are in use.

2024-05-17 18:17 UTC, aefimov3 requested changes
Needs additional testing with reduced render viewport.

2024-05-17 19:17 UTC, alexeykostin commented on Gems/LyShine/Code/Source/UiRenderer.cpp
> +        const AZ::RHI::Viewport& viewport = viewportContext->GetWindowContext()->GetViewport();
I tried to set `r_renderScale=0.7`. When `r_width` is 1680, `r_height` is 1050, the viewport's `m_maxX` is 1176.00000, and `m_maxY` is 735.000000.

When `r_renderScale`=0.7 or `r_renderScale`=1.0,  UI elements are placed correctly, as well as  Input events are translated as expected.

2024-05-17 19:28 UTC, aefimov3 commented on Gems/LyShine/Code/Source/UiRenderer.cpp
> +        const AZ::RHI::Viewport& viewport = viewportContext->GetWindowContext()->GetViewport();
It is good, but please also check user input if it goes to the right buttons. I saw in the debugger that user input comes in screen coordinates.

2024-05-17 20:31 UTC, alexeykostin commented on Gems/LyShine/Code/Source/UiRenderer.cpp
> +        const AZ::RHI::Viewport& viewport = viewportContext->GetWindowContext()->GetViewport();
The buttons are right. I checked in the Windows standalone build.

2024-05-17 21:49 UTC, aefimov3 approved these changes

2024-05-20 17:51 UTC, alexeykostin commented
@Twolewis Could you please take a look

2024-05-21 14:37 UTC, Twolewis commented on Gems/LyShine/Code/Editor/ViewportWidget.cpp
> +#endif
Instead of passing the viewportSize all over the place, can we just request it from LyShine or something?

2024-05-21 14:52 UTC, alexeykostin commented on Gems/LyShine/Code/Editor/ViewportWidget.cpp
> +#endif
`viewportSize` is already optional for `UiCanvasComponent::HandleInputEvent`. If it is nullptr, the canvas size is taken from uiRenderer. Please see 

https://github.com/carbonated-dev/o3de/pull/255/files#diff-ac1cecffa744a9e42411b0e8e485b59457a37c33d9c7bc31b16f1d3c0d593eabR1211

There might be cases when it is not the same as the input one. This needs to be investigated.

2024-05-21 14:56 UTC, Twolewis commented
Additionally - @alexeykostin - have you guys run this by the o3de discord folks to get their thoughts?

2024-05-21 16:31 UTC, Twolewis commented on Gems/LyShine/Code/Editor/ViewportWidget.cpp
> +#endif
No, I'm suggesting to not just pass around the viewport via parameters.  Instead, query it - through a bus call or going to the uicanvas or something.

2024-05-21 20:06 UTC, alexeykostin commented on Gems/LyShine/Code/Editor/ViewportWidget.cpp
> +#endif
We can remove the new viewportSize parameter, but in this case getting the viewport will take extra clock cycles. So this is a potential performance issue.

2024-05-21 20:15 UTC, Twolewis commented on Gems/LyShine/Code/Editor/ViewportWidget.cpp
> +#endif
From what I can tell, passing the viewport size is largely done for input right?  If so, I don't think there will be much of a performance impact.

2024-05-22 15:11 UTC, Twolewis approved these changes

2024-05-22 15:11 UTC, alexeykostin commented on Gems/LyShine/Code/Editor/ViewportWidget.cpp
> +#endif
Normally, there are seldom input events on devices. On Windows if the user hovers the mouse each move translates to an input event. Hopefully, this won't degrade the performance as well.

2024-05-22 17:26 UTC, merged