Carb junho/mad 15510 editor motion set fix
carbonated-dev/o3de pull request #269
Opened 2024-06-08 02:49 UTC by carb-junho

## What does this PR do?

This is for fixing the issue where the derived motionset was not set correctly if the derived motionset gets ready before QueueLoad() was attempted. This caused alternative gender motionset for shotgun and assault from being set correctly.

## How was this PR tested?

The changes were tested on Editor(testing on device right now)

## Ticket Number

[MAD-15510](https://jira.carbonated.com:8443/browse/MAD-15510)

2024-06-08 02:54 UTC, carbonated-niko approved these changes

2024-06-08 09:32 UTC, carb-junho commented
It seems like the asset gets set, but the override for does not get saved. Need to look into how the override works for these

2024-06-13 16:24 UTC, Twolewis commented on Gems/EMotionFX/Code/Source/Integration/Editor/Components/EditorApplyMotionSetComponent.cpp
> +                                if (!m_derivedMotionSetAsset.QueueLoad() || m_derivedMotionSetAsset.IsReady())
Since this is in engine, please guard with
#if defned(CARBONATED)
// new code
#else
// existing code
#endif

2024-06-13 16:25 UTC, Twolewis requested changes
Requesting CARBONATED guards :)

2024-06-13 17:02 UTC, carbonated-niko commented
Oh but also this creates a cycle

2024-06-18 17:19 UTC, closed without merging