Loading screen support
carbonated-dev/o3de pull request #290
Opened 2024-07-03 19:55 UTC by vmednonogov

Ticket [15138]

## What does this PR do?

Added/modified components for loading screen support

## How was this PR tested?

Tested  locally on PC.

Do not merge until:
1) compilation is verified on Jenkins
2) code work is verified on iOS device

Note: this PR requires some additional resources on the game side. If they are missed PR does nothing.

2024-07-22 23:55 UTC, Twolewis requested changes
How is LoadScreenComponent different from LyShineLoadScreen?  It seems more appropriate to fix LyShineLoadScreen instead of adding our own component (from legacy LY code)?

2024-07-22 23:55 UTC, Twolewis commented on Gems/LyShine/Code/Source/LyShineLoadScreen.cpp
> +#if !defined (CARBONATED)
Please reverse these
#if defined(CARBONATED)
..
#else
#endif

it helps to stay consistent.
(and same with other instances of !defined)

2024-07-23 00:00 UTC, Twolewis approved these changes

2024-07-23 21:13 UTC, merged

2024-07-23 21:26 UTC, vmednonogov commented
Verified via Jenkins iOS build: 26389