Don't copy pak assets from APK to SD
carbonated-dev/o3de pull request #318
Opened 2024-09-26 13:33 UTC by alexeykostin

## What does this PR do?

Don't copy pak assets from APK to SD. During APK assembly pak assets stored in it without compression. This alleviates the previously existed issue with a very low reading rate of pak data due to double compression.

Additionally the PR fixes the issue with copying the AWS certificate from the pak to device storage. The issue was observed as a side-effect of non-copying paks from APK to the storage. When paks used to be copied, the target path was created correctly by means of the Java code. Now on a new device, this directory structure has to be created solely by the code of `CopyCaCertBundle()`. It is proved to fail as is, at least on Samsung S23+. The changes include the fix in the `LocalFileIO::CreatePath`, as well as the fix and safer code reorganization of `CopyCaCertBundle()`.

## How was this PR tested?

Tested on Samsung S23+

2024-09-26 13:44 UTC, aefimov3 approved these changes

2024-09-27 14:17 UTC, alexeykostin commented on Code/Framework/AzFramework/Platform/Android/AzFramework/IO/LocalFileIO_Android.cpp
> +#else
This code is unsafe since the beginning of the path may be an existing symlink. If skip `Exists` check, the later `IsDirectory` check would return `false`, and the path creation fails.

2024-09-27 14:17 UTC, Twolewis requested changes

2024-09-27 14:17 UTC, Twolewis commented on Code/Tools/AWSNativeSDKInit/source/Platform/Android/InitializeCerts_Android.cpp
> +#endif
Looks like this is a redundant file close - see line 67

2024-09-27 14:26 UTC, alexeykostin commented on Code/Tools/AWSNativeSDKInit/source/Platform/Android/InitializeCerts_Android.cpp
> +#endif
We need to close it only when `#if !defined(CARBONATED)`

2024-09-27 14:31 UTC, Twolewis requested changes

2024-09-27 14:31 UTC, Twolewis commented on Code/Tools/AWSNativeSDKInit/source/Platform/Android/InitializeCerts_Android.cpp
> +#endif
Oh I see - please do this instead:
```
#if defined(CARBONATED)
  // Removed - closed earlier
#else
fileBase->Close(fileHandle);
#endif
```

It makes subsequent engine merges easier to identify

2024-09-27 14:42 UTC, alexeykostin commented on Code/Tools/AWSNativeSDKInit/source/Platform/Android/InitializeCerts_Android.cpp
> +#endif
Done

2024-09-30 16:03 UTC, Twolewis approved these changes

2024-09-30 18:35 UTC, merged