Az/silhouette improvements
carbonated-dev/o3de pull request #70
Opened 2023-10-05 23:30 UTC by AMZN-alexpete

## What does this PR do?

- revert bufferview change that would likely lead to invalid row calculations
- avoid per-frame filters and use cached pass pointers instead

## How was this PR tested?

- Tested in custom level in windows editor
- used r_silhouette cvar to turn feature on/off
- turned the camera in game to look away and then back again at the silhouettes to verify there were no issues when out of frame

2023-10-05 23:54 UTC, VickyAtAZ requested changes
I think these pass pointers need to assigned in OnRenderPipelineChanged function so they would be set to nullptr properly in case the render pipeline was removed. 
Also, you may want to set them to nullptr too in the beginning of AddRenderPasses function.

2023-10-10 17:54 UTC, carb-lloyd commented
@AMZN-alexpete  - thoughts on the change requests from @VickyAtAZ ?

2023-10-10 19:51 UTC, AMZN-alexpete commented
> @AMZN-alexpete - thoughts on the change requests from @VickyAtAZ ?

I think they're good suggestions and I'm testing them now - just waiting on 8k assets to finish processing 😄

2023-10-12 23:09 UTC, AMZN-alexpete commented
I've implemented and tested the suggestions on PC in editor - should be good to review.

2023-10-16 20:54 UTC, VickyAtAZ commented on Gems/Atom/Feature/Common/Code/Source/Silhouette/SilhouetteFeatureProcessor.cpp
> +        UpdatePasses(pipeline);
This function is called when a RenderPipeline is removed too. 
you may want to handle that case

2023-10-17 22:44 UTC, moudgils approved these changes

2023-10-17 23:09 UTC, VickyAtAZ approved these changes

2023-10-18 16:59 UTC, merged